### ISSUE TITLE
Remove Kint references

### ISSUE THREAD

**Issue by Fuhrmann** [VolantisDev/CakePHP-Menu-Plugin#8]
Not an issue!

I just found some code that make reference to the helper Kint but it is not used in MenuRendererHelper, line 20:

<code>var $helpers = array('Html', 'Kint.Kint');</code>

**Comment by ReplicaObscura** [comment]
Thanks very much, I had left that bit in while testing (it makes use of my Kint plugin) on accident. I'll get that removed and pushed ASAP.

I appreciate you taking the time to report that!

Ben

**Comment by ReplicaObscura** [comment]
FYI, this commit has been pushed. Thanks again!
